Refactor tests
VasekPurchart/Tracy-Blue-Screen-Bundle pull request #30
Opened 2023-04-10 11:15 UTC by petrduda

- [x] stop calling static methods in tests as non-static
- [x] use assertSame() where assertEquals() is not explicitly needed
- [x] use assertCount() after assertContains() for array comparison
- [x] add missing Assert::fail() in try+catch blocks when expecting exceptions
- [x] unify Assert::fail() message
- [x] replace Consistence\TestCase::ok() with expectNotToPerformAssertions()
- [x] use try+catch+fail when expecting exceptions with properties
- [x] rename data providers to singular where applicable
- [x] use DataProvider suffix for data providers
- [x] change data provider return type from array to Generator
- [x] declare data provider values on separate lines
- [x] isolate data provider cases using Closures
- [x] name data provider values
- [x] name data provider cases
- [x] extract multiple cases from test methods to data providers
- [x] remove unnecessary private methods for creating mocks

2023-04-11 15:03 UTC, VasekPurchart requested changes

2023-04-11 15:03 UTC, VasekPurchart commented on tests/DependencyInjection/TracyBlueScreenExtensionConsoleTest.php
> deduplicate testing enabling container service for console using data provider

probably testing of?
\+ the same in next commit

2023-04-11 15:17 UTC, VasekPurchart requested changes

2023-04-11 15:17 UTC, VasekPurchart commented on tests/DependencyInjection/TracyBlueScreenExtensionConsoleTest.php
> +			'configurationValues' => [],
I just noticed we have here `configurationValues` vs `configuration` in (`configureContainerParameterDataProvider()`). These are the same thing, so it is confusing to have both and I think `configuration` is better in this case ("values" is not really helpful :D).

2023-04-12 07:05 UTC, petrduda commented on tests/DependencyInjection/TracyBlueScreenExtensionConsoleTest.php
Ok, reworded.

2023-04-12 07:08 UTC, petrduda commented on tests/DependencyInjection/TracyBlueScreenExtensionConsoleTest.php
> +			'configurationValues' => [],
Fair point, I renamed it to `configuration` here as well as in the two following commits.

2023-04-12 13:36 UTC, VasekPurchart approved these changes

2024-10-21 15:07 UTC, merged